"""
Workbook inventory pass for the DS-NKh-Sentence Maker.

Run twice on the same file:
  - data_only=True  -> last-cached values
  - data_only=False -> formula strings
We print both side-by-side for a small sample of each sheet, plus a structural summary.

Output is plain text on stdout; redirect into notes/sentence_maker_inventory.md.
"""

from __future__ import annotations

import io
import sys
from collections import Counter
from pathlib import Path

# Force UTF-8 stdout/stderr on Windows so Khuzdul Unicode (macrons, schwa, etc.)
# survives a redirect into a markdown file.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
else:  # pragma: no cover - very old Python
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

from openpyxl import load_workbook
from openpyxl.workbook.defined_name import DefinedName

WORKBOOK = Path(__file__).resolve().parent.parent / "sentence_maker_original_v1.xlsm"
SAMPLE_ROWS = 5
SAMPLE_COLS = 10


def summarize_sheet(ws, formulas_ws) -> list[str]:
    lines: list[str] = []
    lines.append(f"### Sheet: `{ws.title}`")
    lines.append("")
    lines.append(f"- State: `{ws.sheet_state}`")
    lines.append(f"- Dimensions: `{ws.dimensions}`  (max_row={ws.max_row}, max_col={ws.max_column})")

    # Count non-empty cells and formulas
    non_empty = 0
    formula_cells = 0
    formula_samples: list[tuple[str, str, object]] = []  # (coord, formula, cached_value)

    for row_idx, row in enumerate(formulas_ws.iter_rows(values_only=False), start=1):
        for cell in row:
            if cell.value is None:
                continue
            non_empty += 1
            if isinstance(cell.value, str) and cell.value.startswith("="):
                formula_cells += 1
                if len(formula_samples) < 12:
                    cached = ws.cell(row=cell.row, column=cell.column).value
                    formula_samples.append((cell.coordinate, cell.value, cached))

    lines.append(f"- Non-empty cells: {non_empty}")
    lines.append(f"- Formula cells: {formula_cells}")
    lines.append("")

    # Header preview (top-left rectangle of values)
    lines.append(f"**Top-left preview ({SAMPLE_ROWS}x{SAMPLE_COLS}) — cached values:**")
    lines.append("")
    lines.append("```")
    for r in range(1, min(SAMPLE_ROWS, ws.max_row or 0) + 1):
        cells = []
        for c in range(1, min(SAMPLE_COLS, ws.max_column or 0) + 1):
            v = ws.cell(row=r, column=c).value
            cells.append("" if v is None else str(v).replace("\n", " ")[:24])
        lines.append(" | ".join(f"{x:<24}" for x in cells))
    lines.append("```")
    lines.append("")

    if formula_samples:
        lines.append("**Formula samples (cell, formula, cached value):**")
        lines.append("")
        lines.append("```")
        for coord, formula, cached in formula_samples:
            cached_str = "" if cached is None else str(cached).replace("\n", " ")[:32]
            lines.append(f"{coord:>6}  =>  {formula[:80]:<80}  =>  {cached_str}")
        lines.append("```")
        lines.append("")

    return lines


def main() -> int:
    if not WORKBOOK.exists():
        print(f"ERROR: workbook not found at {WORKBOOK}", file=sys.stderr)
        return 1

    print(f"# Sentence Maker workbook inventory\n")
    print(f"- Source file: `{WORKBOOK.name}`")
    print(f"- Size: {WORKBOOK.stat().st_size:,} bytes")
    print(f"- Generated by: `scripts/inspect_workbook.py`")
    print()

    wb_values = load_workbook(WORKBOOK, data_only=True, keep_vba=True, read_only=False)
    wb_formulas = load_workbook(WORKBOOK, data_only=False, keep_vba=True, read_only=False)

    # Workbook-level metadata
    print("## Workbook metadata\n")
    print(f"- Sheet count: {len(wb_values.sheetnames)}")
    print(f"- Sheet names (in order):")
    for i, name in enumerate(wb_values.sheetnames):
        ws = wb_values[name]
        print(f"  {i+1:>2}. `{name}`  state=`{ws.sheet_state}`  dims=`{ws.dimensions}`")
    print()

    print(f"- VBA blob present: `{bool(getattr(wb_values, 'vba_archive', None))}`")
    print()

    # Defined names (named ranges)
    print("## Defined names (named ranges)\n")
    defined_names = wb_formulas.defined_names
    names = list(defined_names)
    print(f"- Count: {len(names)}\n")
    if names:
        print("```")
        for name in names:
            dn: DefinedName = defined_names[name]
            try:
                dests = list(dn.destinations)
            except Exception:
                dests = []
            value = dn.value if hasattr(dn, "value") else getattr(dn, "attr_text", "?")
            print(f"{name:<28}  ->  {value}")
        print("```")
    print()

    # Per-sheet detail
    print("## Per-sheet detail\n")
    for name in wb_values.sheetnames:
        ws = wb_values[name]
        fws = wb_formulas[name]
        for line in summarize_sheet(ws, fws):
            print(line)

    # Formula-function frequency across the whole workbook
    print("## Formula function frequency\n")
    func_counter: Counter[str] = Counter()
    for sheet_name in wb_formulas.sheetnames:
        fws = wb_formulas[sheet_name]
        for row in fws.iter_rows(values_only=True):
            for v in row:
                if isinstance(v, str) and v.startswith("="):
                    # crude function-name extraction
                    token = ""
                    for ch in v[1:]:
                        if ch.isalpha() or ch == "_":
                            token += ch
                        else:
                            if token:
                                func_counter[token.upper()] += 1
                            token = ""
                            if ch == "(":
                                continue
                    if token:
                        func_counter[token.upper()] += 1
    # Drop tokens that are obviously cell refs (one or two letters + only digits afterwards) — done above by not capturing digits
    # Show top 40
    print("```")
    for fn, count in func_counter.most_common(40):
        print(f"{fn:<20}  {count}")
    print("```")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
